#!/bin/sh

# Get the git base directory
git_dir=$(git rev-parse --show-toplevel)

# Find js and json files in index, for linting
for file in $(git diff-index --name-only --diff-filter=ACM --cached HEAD -- \
    | grep -P '\.((js)|(json))$'); do
jshint $file 2> /dev/null

# If linting failed, exit with non-zero status and print the error.
if [ $? -ne 0 ] ; then
    echo "Lint check of JSON object failed. Your changes were not commited."
    echo "in $git_dir/$file:"
    jshint $file
    exit 1
fi
                                            done
